<?php

namespace Database\Seeders;
use App\Models\Post;
use App\Models\Media;
use App\Models\Museum;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create audio media (shared for all posts)
        $audioMedia = Media::create([
            'type' => 'audio',
            'url' => [
                'it' => '/assets/collections/audio/164689__deleted_user_2104797__phone_voice_cartoon.wav',
                'en' => '/assets/collections/audio/164689__deleted_user_2104797__phone_voice_cartoon.wav',
            ],
            'title' => [
                'it' => 'Audio guida Opera',
                'en' => 'Collection Audio Guide',
            ],
            'description' => [
                'it' => 'Introduzione audio alla Opera',
                'en' => 'Audio introduction to the collection',
            ],
        ]);

        // Create 11 posts, each with 1 image and the same audio
        $postNames = ['Introduzione', 'Bozzetti per la decorazione murale dello showroom Olivetti a New York, 1953', 'Ruth e Pietro in cucina (Natura morta con Ruth Guggenheim), 1946, olio su tela, collezione MAN', 'Figura femminile, da “Gli antenati”, 1952', 'Bozzetto per la facciata (...) Hartford, Connecticut, 1957-1958', 'Figura maschile, Pastore Sardo, 1966', 'Pergola Village, progetto per Orani, 1953', 'Tre dipinti della serie Ritratti di sculture, 1975', 'Modelli per vari monumenti (unico punto), 1957-1968', 'La città incredibile, 1979', 'Madre, da modello, 1981-1985', 'La stanza delle terrecotte'];
        $postDescriptions = [
            'Titinu: Oh ciao! Non vi avevo notato! Vi state guardando intorno curiosi o vi state chiedendo che strano posto è questo? In effetti anche io, la prima volta che sono arrivato ero un po’ stupito. Era la prima volta che notavo questa breve scala che scendeva verso un giardino silenzioso. Mi sembrava un posto interessante e così, subito, mi ci sono infilato. Mi è sembrato subito un posto magico, un po’ misterioso e nascosto rispetto a tutti quelli che passavano, in macchina o a piedi, sulla strada lì  vicino. Arrivato nel giardino mi sono guardato intorno: avevo ragione, quel posto non  era come tutti gli altri! Gli alberi, dalle foglie scure, mi proteggevano dal sole e  tutt’intorno correvano dei piccoli canali con dell’acqua ma non era quello a stupirmi di  più. Voltandomi a destra e a sinistra vedevo delle figure silenziose: statue  completamente bianche o nere, altre che non capivo bene cosa raffigurassero. A quel  punto un po’ di curiosità mi era venuta: in che posto ero capitato? Cosa  rappresentavano quelle statue? Alcune mi ricordavano delle persone, ma non ero  proprio sicuro. Dovevo assolutamente indagare! Così ho camminato fino alla porta,  sono entrato e ho sceso le scale. In quelle due sale c’era di tutto: quadri con mille  dettagli e bandiere piccolissime, così piccole che quasi non le vedevi, strane sculture  con delle corna e il pianeta terra tutto ricoperto di piccole figurine di bronzo! Anche i  materiali erano un po’ strani e non mi sembravano quelli che usiamo quando facciamo  le ore di arte: c’era il ferro, dei tessuti e persino delle sculture in cemento: come quello  dei muri o dei marciapiedi. Ci ho messo un po\' a mettere ordine le idee, ho dovuto chiedere a un po’ di persone e sono tornato più di una volta. Ora  potrei quasi definirmi un esperto! Ho scoperto che tutte quelle opere, tutti quegli oggetti  strani, avevano un significato profondo ma semplice, che chiunque può capire. Come  se non bastasse dietro c’erano delle mani speciali: le mani di un uomo coraggioso con  una vita davvero avventurosa. Per saperne di più dobbiamo scendere le scale.. Ah, aspettate, non vi ho raccontato nulla su di me: Orani è la mia casa e io abito  proprio qui vicino, in fondo alla strada. La mia famiglia e i miei amici mi chiamano tutti  Titinu, potete chiamarmi così anche voi. Ora entriamo, vi faccio conoscere una persona  speciale.',
            'Titinu: Rieccomi! Vi state chiedendo cosa sono queste figure? In che modo vanno guardate e in che strano materiale sono fatte? Capisco… anche io all’inizio avevo le stesse domande. Per ora posso dirvi solo che le ha create quella persona dalle mani speciali di cui vi raccontavo prima, il suo nome era Costantino Nivola. Ma per capirci qualcosa di più la persona a cui dobbiamo chiedere è Ruth: lei sa tutto. Ruth: Oh eccoti Titinu e dietro di te vedo alcune facce nuove! Che bello essere qui con voi e potervi raccontare delle avventure che ho attraversato e di Costantino, Antine come lo chiamavo io, che è stato con me in ogni momento. Il mio nome è Ruth Guggenheim. Come? Cosa dite? Vi sembra un cognome particolare? Beh, avete ragione! La mia famiglia era di origine ebraica e io sono nata in Germania in un anno che ora sembra lontanissimo: il 1917. Erano anni molto duri: anche se ero solo una bambina ricordo bene mio padre preoccupato perchè in Germania si moltiplicavano i crimini e le violenze contro gli ebrei. Così scappammo in Italia, senza sapere che anche lì i guai ci avrebbero raggiunto… ma questo ve lo racconterò più avanti. A quel punto non ero più una bambina ma una ragazza di 16 anni. Anche se avevo cambiato stato e città le mie passioni restavano intatte: mi interessava l’arte e adoravo creare. Così mi iscrissi all’Istituto d’Arte ed è stato proprio lì che ho incontrato Antine. Devo dire che notarlo non era difficile: in tutta la scuola, che era a Monza, c’erano solo tre ragazzi sardi che stavano sempre insieme ed erano uno più talentuoso dell’altro. Io e Antine ci siamo piaciuti subito e infatti poi non ci siamo più lasciati anche se venivamo da mondi molto diversi, lui da un piccolo paese della Sardegna e io da una grande città tedesca. Ogni opera di questo museo mi ricorda un momento diverso della nostra vita insieme. Qui, per esempio, Antine aveva appena ottenuto un lavoro importante. Provate a immaginare di essere sulla Fifth Avenue a New York, una delle strade più famose del mondo. Auto, taxi gialli, persone che camminano veloci, grattacieli altissimi. In mezzo a tutto questo, negli anni Cinquanta, c’era un negozio speciale della ditta Olivetti, dove si vendevano macchine da scrivere e calcolatrici, ma anche un’idea nuova di bellezza e di lavoro. Adriano Olivetti, il direttore, pensava che le persone, quando entravano in un luogo di lavoro, meritassero di trovare anche armonia, luce, bellezza. Per questo chiamò architetti e artisti moderni, e tra questi c’era proprio Antine. I bozzetti che vedi qui sono i suoi primi pensieri per decorare le pareti e i muri del negozio. Era un’idea rivoluzionaria: per vedere l’arte non si doveva più entrare in un museo ma era lì, mescolata alle cose di tutti i giorni. Ma ora andiamo avanti voglio mostrarvi un’altra opera…',
            '«Ora vi porto in un luogo molto diverso dalle strade newyorkesi e dai negozi pieni di persone. Una piccola stanza così ricca di colori e di oggetti da rendere quasi difficile
distinguerli tutti. Sono molto legata a questo quadro perchè sulla destra ci sono proprio io, Ruth e un po’ più in alto, quasi come se stesse galleggiando in aria, c’è Pietro, il nostro primogenito. Come vedi non sono più una giovane ragazza ma una donna. Se guardi ancora più da vicino vedrai che ho un’espressione concentrata e un po’ seria. Per forza! A quel punto io e Antine avevamo già affrontato mille difficoltà! Pochi anni dopo che ci eravamo conosciuti anche in Italia vennero approvate le leggi razziali e per gli ebrei la vita divenne ancora più difficile. Così io e Antine, pur di stare insieme, decidemmo di scappare insieme in America. Sembra una vera avventura ma in realtà fu molto difficile: Antine non parlava bene l’inglese e fece molta fatica a trovare un lavoro. Io invece lo conoscevo un po’ meglio e cominciai a lavorare in una fabbrica e poi come bambinaia. Pian piano le cose migliorarono: Antine trovò un lavoro che gli piaceva tantissimo, come grafico per le riviste americane e conoscemmo alcuni dei più grandi artisti e architetti di quel tempo, tra cui Le Corbusier che divenne suo grande amico. Il quadro che hai davanti al naso è proprio di quel periodo: la nostra casa era il suo rifugio. In questo dipinto mi vedi mentre preparo da mangiare, circondata da piatti, frutta, bottiglie. Potrebbe sembrare una scena comune, come quella che vedi a casa tua ogni giorno. Eppure, per Antine, questo era un soggetto importantissimo: la vita quotidiana, la cura per gli altri. Se guardi il quadro più da vicino scoprirai molti dettagli: la nostra cena, la lampada che pende dal soffitto ma anche i pennelli e la tavolozza che Antine usava tutti i giorni. Anche i colori mi ricordano una coperta calda e mi fanno subito sentire a casa. La prossima opera ve la racconterà Titunu, ormai la conosce benissimo ed è una delle sue preferite.',
            'Titinu: Di questa figura vorrei parlarvi io perchè la prima volta che l’ho vista ho pensato che fosse un po’ come un mistero da scoprire. Come se Nivola stesse cercando di dirmi qualcosa che però, a prima vista, mi sfuggiva. Il colore mi ricordava quello di un chiodo che viene lasciato all’aperto per molto tempo e si arrugginisce. La figura  all’inizio mi intimoriva un po’, poi ho notato che si curvava verso di me, come in un abbraccio verso tutto quello che gli stava davanti. Ho guardato il cartellino che gli stava a fianco sicuro che mi avrebbe aiutato: in piccolo c’era scritto “Figura femminile dalla serie “Gli Antenati”. Io sapevo che gli antenati erano come i nonni dei nonni, persone vissute molto tempo prima di noi. Quindi, nell’idea di Nivola, quella figura era come una nonna di un’epoca molto molto lontana. La cosa più curiosa è che però Nivola, per crearla, non aveva utilizzato una pietra, scolpito un sasso, usato un materiale che sicuramente esisteva anche tantissimo tempo fa. No, lui aveva utilizzato del ferro, una lamiera mi ha poi spiegato Ruth, che era un materiale comunissimo a New York e in Italia e si usava per costruire grattacieli e palazzi modernissimi. In questa figura si uniscono così due mondi molto diversi, i nonni dei nonni, un tempo molto antico e un materiale moderno che le persone della stessa età di Nivola vedevano e usavano tutti i giorni. Forse era il suo modo per dirci che anche nelle nostre vite veloci e tecnologiche restiamo legati con un filo sottile a tutte le persone che sono venute prima di noi e che hanno sognato, desiderato e si sono poste delle domande proprio come facciamo noi. Ma questa è solo la mia idea ed è possibile che mi sbagli! Sono molto curioso di sapere cosa ne pensate voi, cosa vi ricorda questa figura e come vi fa sentire.',
            'Rieccovi! Vi stavo aspettando. Ci troviamo di fronte a… come dici? Tu, là in fondo con la frangetta, quest’opera ti ricorda… un muro? Un muro un po’ particolare con delle forme, delle fossette, delle figure? Io non me la prendo di certo e sono sicura che anche Antine si farebbe una bella risata perché non hai proprio torto. Quest’opera speciale è realizzata proprio in cemento, lo stesso dei muri di casa o dei cordoli dei marciapiedi. Antine lo conosceva bene perché quando era ancora piccolo aveva cominciato a lavorare come manovale e poi come muratore, come il suo babbo. Devi sapere che Orani era famosa per i suoi muratori e lui lo è stato. Poi aveva preso un’altra strada, si era innamorato dell’arte ma quello che aveva imparato a Orani non l’ha mai dimenticato. Così ha trovato un modo per unire il lavoro di muratore e quello di artista. Vuoi sapere un altro segreto? La tecnica che Antine ha utilizzato per quest’opera l’aveva scoperta giocando! Sì, avete capito bene, giocava con i nostri due bambini al mare con la sabbia, come fate anche voi d’estate e così gli è venuta l’idea di utilizzarla come stampo. Creava un disegno sulla sabbia e poi, piano piano, ci faceva colare sopra il cemento. Quando il cemento era asciutto lo staccava e restavano impresse tutte queste figure che vedete. Gli architetti adoravano queste opere! Perché erano opere artistiche ma resistenti, dello stesso materiale dei palazzi che stavano costruendo e si potevano trasportare senza rischi. Così ebbero tantissimo successo e Antine ne creò molte per tantissimi palazzi in America. Il suo era anche un modo di dire che l’arte poteva stare ovunque: sui palazzi del governo, negli uffici, in mezzo alle città. L’arte e la bellezza secondo lui dovevano essere a disposizione di tutti e potevano migliorare la società. Era un grande sogno e Antine non ha mai smesso di coltivarlo.',
            'Un’altra opera, un altro materiale: questa volta un tessuto, come un tappeto disegnato. Anche voi come me vi siete chiesti: ma quante cose sapeva fare questo Nivola? Il cemento, la pietra, la sabbia, il ferro e ora anche la stoffa. Però devo rivelarvi che qui ha avuto un aiutino. Come vi raccontava Ruth a Nivola piaceva molto l’idea che l’arte entrasse nella vita di tutti i giorni, negli uffici e nelle case. Lui però era uno scultore e non tutti hanno spazio per delle sculture in casa, senza contare che pesano molto e potrebbero rompersi. Così ne parlò con un suo caro amico architetto che si chiamava Le Corbusier, che gli diede un suggerimento geniale: perché non rendi le tue sculture leggere e sottili? Una bella idea per il mondo moderno in cui le persone cambiano spesso casa e gli spazi sono piccoli. Nivola lo prese in parola e fece diversi disegni delle sue sculture e poi li inviò a un piccolo paese della Sardegna che si chiama Sarule ed è famoso per le sue tessitrici. La sua idea era trasformare le sculture di pietra in arazzi, che sono come dei grandi tappeti che si appendono ai muri. Quello che vedi appeso davanti a te è proprio uno di quegli arazzi. Nivola qui ha disegnato un pastore sardo, forte e solido mentre accompagna il suo gregge per i campi e le montagne. Anche se in quel periodo viveva negli Stati Uniti non ha mai dimenticato le colline intorno a Orani, le campane delle pecore, i muretti a secco. Disegnare queste figure era un po’ come dire: “Non mi dimentico da dove vengo.” Quando l’arazzo fu finito le tessitrici di Sarule che lo avevano realizzato dissero che era davvero bello, per Nivola fu un grande complimento.',
            'Sono di nuovo io! In queste opere si parla di Orani e dato che vivo proprio qui dovevo assolutamente parlarvene. Questi disegni con foglie, muretti, persone e animali è un grande sogno di Costantino Nivola: si chiama “Pergola Village” che vuol dire, più o meno, paese pergolato. I pergolati sono quelle strutture in legno o in ferro a cui si arrampicano diversi tipi di piante, viti, rose o glicini, in estate le foglie fanno ombra mentre d’inverno cadono lasciando passare la luce. Ecco, Nivola ha immaginato che tutte le case di Orani fossero collegate da dei pergolati così che camminare per il paese diventasse come camminare in un giardino, al fresco e circondati da foglie e fiori. È un’idea meravigliosa che va oltre la scultura, oltre la pittura e tutte le altre cose che aveva fatto fino a quel momento. In questo progetto le persone possono chiacchierare sedute fuori casa senza bruciarsi al sole o bagnarsi troppo quando piove. Nivola, che era partito da questo piccolo paese per arrivare fino a New York, non si è mai dimenticato di Orani. Anzi, più era lontano, più ci pensava. Diceva di sentirsi come un anello staccato dalla sua catena. Disegnando questo progetto, voleva regalare al suo paese una specie di abbraccio fatto di case, colori e piante accrescendo così il senso di comunità e di unione tra gli abitanti. Se guardi le altre tavole troverai molte altre caratteristiche di Orani che Antine ricordava bene dalla sua infanzia: donne che fanno il pane e lo infornano, asinelli che trasportano la legna. Il progetto che vedi fu pubblicato su un’importante rivista in America: lì, persone che non avevano mai sentito nominare Orani si sono messe a studiare queste casette sarde tutte coperte di verde. ',
            'In questa sala succede qualcosa di curioso: Antine non ritrae persone, ma… le sue stesse sculture. È come se avesse preso le opere tridimensionali che aveva già creato – quelle fatte di cemento, pietra o altri materiali – e avesse deciso di guardarle di nuovo, questa volta con gli occhi del pittore. I dipinti che vedi fanno parte della serie che lui chiamava “Ritratti di sculture”. Quando trasformi una scultura in un dipinto, molte cose cambiano: la profondità diventa superficie, le ombre diventano colore, il volume viene tradotto in linee. Nivola usava questa trasformazione per capire meglio le sue stesse forme: le tagliava con lo sguardo, le semplificava, le esagerava, a volte le rendeva quasi irriconoscibili. Era un dialogo continuo tra il suo lavoro di scultore e quello di pittore. Osservando questi tre dipinti, puoi provare a immaginare quali parti corrispondano a curve, a spigoli, a rientranze delle sculture originali. Ma non è importante indovinare con precisione: quello che conta è cogliere il modo in cui il colore sostituisce la materia. Le tinte sono spesso intense, non realistiche, perché non vogliono imitare la superficie della scultura; vogliono raccontare la sua energia interna, il suo carattere. In un certo senso, questi quadri sono anche un esercizio di memoria: Antine guarda indietro alla sua produzione, la ripercorre, la riassume, la ricrea su tela. È come se scrivesse il ritratto di una persona che conosce benissimo – se stesso – usando però, al posto delle parole, le forme delle sue opere. ',
            '«Orani era la prima casa di Antine, lì aveva la sua famiglia e i ricordi della sua infanzia, ma anche gli Stati Uniti per noi sono stati importantissimi. Lì abbiamo vissuto per quasi tutta la nostra vita adulta, cresciuto i nostri bambini, sperimentato e creato. Non eravamo diversi dalle moltissime persone che partivano cercando il “sogno americano”, possibilità e benessere. Come hai visto Antine ha sperimentato un po’ di tutto: pittura, scultura, architettura. In questo caso aveva immaginato un grande monumento che rappresentava il simbolo americano per eccellenza: la sua bandiera. La sua idea era di creare una bandiera americana gigantesca: le onde che vedi sarebbero diventate muri e le stelle delle altissime colonne. Prova ad avvicinarti con gli occhi. Le strisce non sono lisce: somigliano a onde di mare o a dune scolpite dal vento. Le stelle, invece, non sono stampate ma diventano piccole forme tridimensionali in cima a tante aste sottili, come se stessero facendo un salto verso il cielo. È un trucco che Nivola usava spesso: prendere qualcosa di piatto e farlo esplodere nello spazio, così che tu non possa più limitarti a guardarlo da un solo lato ma debba girargli intorno. Le persone avrebbero potuto camminarci in mezzo liberamente come potevano inseguire il loro sogno in quella terra delle opportunità. La parte più impressionante erano sicuramente le cinquanta colonne a forma di stelle che rappresentavano i cinquanta stati americani. Antine non ha mai guardato gli Stati Uniti a occhi chiusi: conosceva le sue ingiustizie, i suoi difetti. Allo stesso tempo New York, Long Island sono state la nostra seconda casa e lui voleva ricordarla con questo monumento.',
            'Ruth:«Fermati un attimo davanti a questo quadro. All’inizio sembra solo un enorme groviglio nero: linee, riccioli, quadratini che si incastrano uno sull’altro. Ma se stringi un po’ gli occhi, succede qualcosa: quei
segni diventano palazzi, finestre, strade, macchine, persone piccolissime bloccate nel traffico. È una città che esplode di movimento, rumore, confusione. È New York, vista attraverso gli occhi di Antine. Quando siamo arrivati lì, scappando dall’Europa per via delle leggi razziali, tutto ci sembrava incredibile: i grattacieli altissimi, le luci, i ponti, le persone di ogni parte del mondo che camminavano fianco a fianco. Antine era affascinato: appena arrivato dipingeva New York continuamente come se disegnandola potesse capirla meglio. Questo quadro però è molto successivo, Antine ormai vedeva anche l’altro lato: il traffico che non finisce mai, la gente che corre senza guardarsi, le ingiustizie e la povertà nascoste dietro le vetrine luccicanti. In questo quadro non finge che sia tutto perfetto: ti mostra una città bellissima… ma anche stancante, complicata, a volte spietata. È una città di grandi palazzi e con persone da tutto il mondo: riesci a riconoscere tutte le bandiere che Antine ha dipinto? La sua “città incredibile” è un po’ un avvertimento: ci dice che le città sono meravigliose, ma che abbiamo bisogno di fermarci ogni tanto, di non perderci nel groviglio. Guardando questo quadro forse scopri qualcosa che non avevi mai pensato: anche il caos può essere disegnato, osservato, capito. E, soprattutto, possiamo domandarci che tipo di città vogliamo costruire noi, da grandi.» ',
            'Titinu:«Mia nonna mi ha raccontato una cosa curiosa: che più si diventa grandi, proprio  anziani, più si ripensa a quando si era piccoli e quei ricordi lontanissimi diventano quasi  magici. Io penso che qualcosa del genere sia capitato anche a Nivola che più diventava  grande e più scavava nei suoi primissimi ricordi e lì trovava sempre ispirazione. Questa  grande statua tutta bianca, con una piccola curva al centro lui l’ha intitolata “Madre” e  allora capiamo subito bene cos’è: una mamma che aspetta nel suo grembo il segreto di un figlio meraviglioso. Per crearla lui aveva ripensato alla sua casa di quando era piccolo e al “muro  panciuto” dove si cuoceva il pane. Il pane allora era preziosissimo. La curva nel muro, dove si cuoceva il pane, nascondeva quindi un tesoro, la promossa di appagare la fame una volta per sempre, come una madre nasconde nel suo grembo il segreto di un figlio meraviglioso. Nivola  mescola quindi i suoi ricordi con una figura semplice ma molto potente. Questa  mamma sembra aprirsi in un abbraccio verso tutti quelli che gli stanno davanti. Per  scolpirla Nivola sceglie il marmo, una pietra nobile e durissima. Forse ha scelto proprio per  questo motivo, per dire: l’amore dei genitori non si spezza facilmente.',
            'Ruth: «Questa grande sfera scura sembra, a prima vista, un pianeta misterioso perso nello spazio. Avvicinati un po’ di più con lo sguardo: non è liscia come una palla da gioco, la superficie è piena di piccole forme, curve, solchi, rilievi che si intrecciano. È come se qualcuno avesse modellato tante figure minuscole, una accanto all’altra, finché non c’è più neanche un millimetro di spazio libero. Per questo l’opera si chiama “La terra sovrappopolata”: una terra dove ci sono talmente tante presenze da non poterle più contare una per una. Nivola ha lavorato spesso con materiali duri come il cemento o il marmo, ma qui torna a un modo di modellare molto vicino al gioco: impasta, aggiunge, schiaccia, incide. Immagina le sue mani che girano intorno alla sfera, aggiungendo continuamente piccoli segni, come se stesse scrivendo una storia senza parole. Ogni segno può essere una persona, un animale, una casa, un pensiero. Nessuno è grande, nessuno domina sugli altri: tutti insieme formano la pelle del pianeta. In una scultura come questa sembra chiederci: “Cosa succede alla Terra quando diventiamo sempre di più? Proviamo a fare un gioco: scegli con gli occhi un punto qualsiasi della superficie e fissalo per qualche secondo. Cosa ti sembra di vedere? Un volto, un corpo, un animale, o solo una macchia? Ora sposta lo sguardo, ruota un po’ intorno alla sfera e cerca un altro dettaglio. Capirai che l’opera non finisce mai: più la osservi, più scopri forme nuove. E forse ti verrà voglia di pensare anche a questo: se la Terra vera potesse parlare, che cosa direbbe di noi che la abitiamo tutti insieme, stretti stretti sulla sua superficie?”'
        ];
        for ($i = 0; $i <= 11; $i++) {
            $imageMedia = Media::create([
                'type' => 'image',
                'url' => [
                    'it' => "/assets/collections/{$i}.png",
                    'en' => "/assets/collections/{$i}.png",
                ],
                'title' => [
                    'it' => "Immagine {$i} - Collezione",
                    'en' => "Image {$i} - Collection",
                ],
                'description' => [
                    'it' => "Fotografia della collezione - Immagine {$i}",
                    'en' => "Collection photo - Image {$i}",
                ],
            ]);

            $post = Post::create([
                'name' => [
                    'it' => $postNames[$i],
                    'en' => 'English: ' . $postNames[$i],
                ],
                'description' => [
                    'it' => $postDescriptions[$i],
                    'en' => 'English: ' . $postDescriptions[$i],
                ],
                'content' => [
                    'it' => "Contenuto dettagliato del post della collezione {$i}",
                    'en' => "Detailed content of the collection post {$i}",
                ],
                'audio_id' => $audioMedia->id,
                'exhibition_id' => 1, // Adjust as needed
            ]);

            // Attach the image to the post
            $post->images()->attach([$imageMedia->id]);
        }
    }
}
